### ISSUE TITLE
Follow naming conventions

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto-bugtrap-ruby#1]
https://github.com/bigbinary/neeto-engineering-web/issues/244

You can delete the other repo, if you want it for some reason, rename it to have a suffix `-old` until we need it.

@sruthy-j-mallya _a

**Comment by sruthy-j-mallya** [comment]
@sandip-mane 

> You can delete the other repo, if you want it for some reason, and rename it to have a suffix `-old` until we need it.

I do not have access to the settings for both repositories. Can you please rename the repo name? I cloned the first repo (neeto-bugtrap-ruby) into my computer for my reference. If it is not needed you can delete that repo from BigBinary.

**Comment by sandip-mane** [comment]
Done.
